---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/instance: catalog-service-api
configMapGenerator:
- name: pycsw-config
  files:
    - config/pycsw.cfg
- name: postgis-config
  files:
    - config/passwd
resources:
  - postgis.yaml
  - pycsw.yaml

