---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pycsw
  annotations:
    app.kubernetes.io/name: pycsw
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: pycsw
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pycsw
    spec:
      restartPolicy: Always
      containers:
        - name: pycsw
          image: docker.io/geopython/pycsw:2.6.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/pycsw
              name: pycsw-config
      volumes:
        - name: pycsw-config
          configMap:
            name: pycsw-config

---
apiVersion: v1
kind: Service
metadata:
  name: pycsw
  labels:
    app.kubernetes.io/name: pycsw
spec:
  selector:
    app.kubernetes.io/name: pycsw
  # TODO: check if application gets problems, if so - remove clusterIP definition.
  clusterIP: None
  ports:
    - protocol: TCP
      name: http
      targetPort: http
      port: 80


