apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-nginx
  annotations:
    app.kubernetes.io/name: hello-world-nginx
    app.kubernetes.io/instance: s-enda
    app.kubernetes.io/version: v1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-world-nginx
      app.kubernetes.io/instance: s-enda
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello-world-nginx
        app.kubernetes.io/instance: s-enda
    spec:
      containers:
        - name: app
          image: registry.met.no/k8s/nginx-hello-nonroot:v1.0.1
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /run
              name: tmp
              readOnly: false
            - mountPath: /tmp
              name: tmp
              readOnly: false
            - mountPath: /var/lib/nginx/tmp
              name: tmp
              readOnly: false
      volumes:
        - name: tmp
          emptyDir: {}
