apiVersion: v1
kind: Service
metadata:
  name: hello-world-nginx
  labels:
    app.kubernetes.io/name: hello-world-nginx
    app.kubernetes.io/instance: s-enda
    app.kubernetes.io/version: v1.0
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: hello-world-nginx
    app.kubernetes.io/instance: s-enda
