---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/instance: dcmi
configMapGenerator:
- name: dmci-config
  files:
    - config/config.yaml
resources:
  - deployment.yaml

