---
apiVersion: v1
kind: Service
metadata:
  name: mms-http
spec:
  clusterIP:
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: mms-nats
spec:
  clusterIP:
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: nats
      targetPort: nats
      port: 4222
      nodePort:
