---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mms-workdir
  labels:
    app.kubernetes.io/name: mms
    app.kubernetes.io/instance: s-enda
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mms
  annotations:
    app.kubernetes.io/name: mms
    app.kubernetes.io/instance: s-enda
    app.kubernetes.io/version: v1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mms
      app.kubernetes.io/instance: s-enda
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mms
        app.kubernetes.io/instance: s-enda
    spec:
      containers:
        - name: mms
          image: registry.met.no/s-enda/container-go-mms:f92ccde9
          imagePullPolicy: IfNotPresent
          command:
            - /app/mmsd
            - --hostname
            - 0.0.0.0
            - -w
            - /workdir
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: nats
              containerPort: 4222
              protocol: TCP
          volumeMounts:
            - mountPath: /workdir
              name: mms-workdir
              readOnly: false
      volumes:
        - name: mms-workdir
          persistentVolumeClaim:
            claimName: mms-workdir

---
apiVersion: v1
kind: Service
metadata:
  name: mms-http
  labels:
    app.kubernetes.io/name: mms
    app.kubernetes.io/instance: s-enda
spec:
  selector:
    app.kubernetes.io/name: mms
    app.kubernetes.io/instance: s-enda
  clusterIP: None
  ports:
    - protocol: TCP
      name: http
      targetPort: http
      port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: mms-nats
  labels:
    app.kubernetes.io/name: mms
    app.kubernetes.io/instance: s-enda
spec:
  selector:
    app.kubernetes.io/name: mms
    app.kubernetes.io/instance: s-enda
  type: NodePort
  ports:
    - protocol: TCP
      name: nats
      targetPort: nats
      port: 4222
      nodePort: 30313




